resources:
  containers:
  - container: pg11
    image: postgres:11
  - container: pg10
    image: postgres:10

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    postgres11:
      postgresService: pg11
    postgres10:
      postgresService: pg10


services:
  postgres: $[ variables['postgresService'] ]
steps:
  - script: |
      apt install -y postgresql-client
      psql --host=postgres --username=postgres --command="SELECT 1;"